const path = require('path');
const fs = require('fs');
const lunr = require('lunr');


function generateLunrClientJS(language = "en") {
    if (Array.isArray(language) && language.length === 1) {
        language = language[0];
    }
    let lunrClient =
        "// THIS FILE IS AUTOGENERATED\n" +
        "// DO NOT EDIT THIS FILE!\n\n" +
        'import * as lunr from "lunr";\n';

    function importLunrLangPackage(languageCode) {
        if(languageCode === "zh"){
            require(`./lunr.zh`)(lunr);
            lunrClient += `require("docusaurus-lunr-search/src/lunr.zh")(lunr);\n`;
            return;
        }
        require(`lunr-languages/lunr.${languageCode}`)(lunr);
        lunrClient += `require("lunr-languages/lunr.${languageCode}")(lunr);\n`;
    }

    if (language !== "en") {
        require("lunr-languages/lunr.stemmer.support")(lunr);
        lunrClient += 'require("lunr-languages/lunr.stemmer.support")(lunr);\n';
        if (Array.isArray(language)) {
            language
                .filter(code => code !== "en")
                .forEach(importLunrLangPackage);
            require("lunr-languages/lunr.multi")(lunr);
            lunrClient += `require("lunr-languages/lunr.multi")(lunr);\n`;
        } else {
            importLunrLangPackage(language);
        }
    }
    lunrClient += `export default lunr;\n`;

    const lunrClientPath = path.join(__dirname, "lunr.client.js");
    fs.writeFileSync(lunrClientPath, lunrClient);

    if (language !== "en") {
        if (Array.isArray(language)) {
            return lunr.multiLanguage(...language);
        } else {
            return lunr[language];
        }
    }
    return null;
}

function getFilePaths(routesPaths, outDir, baseUrl) {
    const files = []
    routesPaths.forEach((route) => {
        if (route === baseUrl || route === `${baseUrl}404.html`) return;
        route = route.substr(baseUrl.length);
        files.push({
            path: path.join(outDir, route, "index.html"),
            url: route,
        });
    });
    return files;
}

module.exports = {
    generateLunrClientJS,
    getFilePaths
}